#
set_property PACKAGE_PIN D15 [get_ports FPGA_REF_CLK]
#
set_property PACKAGE_PIN E3 [get_ports PLL_FPGA_CLK_P]
#
set_property PACKAGE_PIN U14 [get_ports FPGA_SYS_WORK]
#
set_property PACKAGE_PIN F14 [get_ports {HW_REV[0]}]
set_property PACKAGE_PIN F13 [get_ports {HW_REV[1]}]
set_property PACKAGE_PIN G13 [get_ports {HW_REV[2]}]
#
set_property PACKAGE_PIN M13 [get_ports ARM_FPGA_nCS]
set_property PACKAGE_PIN N14 [get_ports ARM_FPGA_nWE]
set_property PACKAGE_PIN V15 [get_ports ARM_FPGA_nOE]
set_property PACKAGE_PIN U17 [get_ports {ARM_FPGA_ADDR[11]}]
set_property PACKAGE_PIN R16 [get_ports {ARM_FPGA_ADDR[10]}]
set_property PACKAGE_PIN U18 [get_ports {ARM_FPGA_ADDR[9]}]
set_property PACKAGE_PIN J14 [get_ports {ARM_FPGA_ADDR[8]}]
set_property PACKAGE_PIN J18 [get_ports {ARM_FPGA_ADDR[7]}]
set_property PACKAGE_PIN J17 [get_ports {ARM_FPGA_ADDR[6]}]
set_property PACKAGE_PIN U16 [get_ports {ARM_FPGA_ADDR[5]}]
set_property PACKAGE_PIN T14 [get_ports {ARM_FPGA_ADDR[4]}]
set_property PACKAGE_PIN T15 [get_ports {ARM_FPGA_ADDR[3]}]
set_property PACKAGE_PIN V17 [get_ports {ARM_FPGA_ADDR[2]}]
set_property PACKAGE_PIN T16 [get_ports {ARM_FPGA_ADDR[1]}]
set_property PACKAGE_PIN V16 [get_ports {ARM_FPGA_ADDR[0]}]
set_property PACKAGE_PIN K16 [get_ports {ARM_FPGA_DATA[7]}]
set_property PACKAGE_PIN T18 [get_ports {ARM_FPGA_DATA[6]}]
set_property PACKAGE_PIN R15 [get_ports {ARM_FPGA_DATA[5]}]
set_property PACKAGE_PIN K13 [get_ports {ARM_FPGA_DATA[4]}]
set_property PACKAGE_PIN R13 [get_ports {ARM_FPGA_DATA[3]}]
set_property PACKAGE_PIN R12 [get_ports {ARM_FPGA_DATA[2]}]
set_property PACKAGE_PIN M14 [get_ports {ARM_FPGA_DATA[1]}]
set_property PACKAGE_PIN N17 [get_ports {ARM_FPGA_DATA[0]}]
#
set_property PACKAGE_PIN D9 [get_ports PLL_nCS]
set_property PACKAGE_PIN C9 [get_ports PLL_SCLK]
set_property PACKAGE_PIN D10 [get_ports PLL_SDIO]
set_property PACKAGE_PIN C11 [get_ports PLL_REFCLK_SEL]
set_property PACKAGE_PIN C10 [get_ports PLL_HOLD_OVER]
#
set_property PACKAGE_PIN D14 [get_ports {COLUMN[4]}]
set_property PACKAGE_PIN A18 [get_ports {COLUMN[3]}]
set_property PACKAGE_PIN C14 [get_ports {COLUMN[2]}]
set_property PACKAGE_PIN D12 [get_ports {COLUMN[1]}]
set_property PACKAGE_PIN A16 [get_ports {COLUMN[0]}]
set_property PACKAGE_PIN C17 [get_ports {ROW[5]}]
set_property PACKAGE_PIN C16 [get_ports {ROW[4]}]
set_property PACKAGE_PIN C15 [get_ports {ROW[3]}]
set_property PACKAGE_PIN D13 [get_ports {ROW[2]}]
set_property PACKAGE_PIN C12 [get_ports {ROW[1]}]
set_property PACKAGE_PIN B14 [get_ports {ROW[0]}]
set_property PACKAGE_PIN T11 [get_ports KEY_CODE_INT]
set_property PACKAGE_PIN E17 [get_ports CODE_SWITCH_1]
set_property PACKAGE_PIN E18 [get_ports CODE_SWITCH_2]
set_property PACKAGE_PIN B17 [get_ports CH1_LED]
set_property PACKAGE_PIN E15 [get_ports CH2_LED]
set_property PACKAGE_PIN D18 [get_ports MODE_LED]
set_property PACKAGE_PIN D17 [get_ports SYNC_LED]
set_property PACKAGE_PIN T13 [get_ports BUZZER_ON_OFF]
#
set_property PACKAGE_PIN A15 [get_ports CH1_LOAD_PROTECT]
set_property PACKAGE_PIN A13 [get_ports CH1_ON_OFF]
set_property PACKAGE_PIN B12 [get_ports CH1_ATT1_3]
set_property PACKAGE_PIN A10 [get_ports CH1_ATT1_10]
set_property PACKAGE_PIN B13 [get_ports CH1_ATT2_10]
set_property PACKAGE_PIN A11 [get_ports CH1_GAIN_5]
#
set_property PACKAGE_PIN A14 [get_ports CH2_LOAD_PROTECT]
set_property PACKAGE_PIN A9 [get_ports CH2_ON_OFF]
set_property PACKAGE_PIN B8 [get_ports CH2_ATT1_3]
set_property PACKAGE_PIN A8 [get_ports CH2_ATT1_10]
set_property PACKAGE_PIN B11 [get_ports CH2_ATT2_10]
set_property PACKAGE_PIN B9 [get_ports CH2_GAIN_5]
#
set_property PACKAGE_PIN F6 [get_ports AD9122_nCS]
set_property PACKAGE_PIN C7 [get_ports AD9122_SCLK]
set_property PACKAGE_PIN B7 [get_ports AD9122_SDIO]
set_property PACKAGE_PIN D8 [get_ports AD9122_nRESET]
#
set_property PACKAGE_PIN D5 [get_ports CH_DAC_DCI_P]
set_property PACKAGE_PIN J3 [get_ports {CH_DAC_DATA_P[15]}]
set_property PACKAGE_PIN J4 [get_ports {CH_DAC_DATA_P[14]}]
set_property PACKAGE_PIN K2 [get_ports {CH_DAC_DATA_P[13]}]
set_property PACKAGE_PIN H1 [get_ports {CH_DAC_DATA_P[12]}]
set_property PACKAGE_PIN F1 [get_ports {CH_DAC_DATA_P[11]}]
set_property PACKAGE_PIN C2 [get_ports {CH_DAC_DATA_P[10]}]
set_property PACKAGE_PIN B1 [get_ports {CH_DAC_DATA_P[9]}]
set_property PACKAGE_PIN C4 [get_ports {CH_DAC_DATA_P[8]}]
set_property PACKAGE_PIN B3 [get_ports {CH_DAC_DATA_P[7]}]
set_property PACKAGE_PIN A4 [get_ports {CH_DAC_DATA_P[6]}]
set_property PACKAGE_PIN C6 [get_ports {CH_DAC_DATA_P[5]}]
set_property PACKAGE_PIN A6 [get_ports {CH_DAC_DATA_P[4]}]
set_property PACKAGE_PIN E2 [get_ports {CH_DAC_DATA_P[3]}]
set_property PACKAGE_PIN G4 [get_ports {CH_DAC_DATA_P[2]}]
set_property PACKAGE_PIN H2 [get_ports {CH_DAC_DATA_P[1]}]
set_property PACKAGE_PIN E7 [get_ports {CH_DAC_DATA_P[0]}]
#
set_property PACKAGE_PIN F16 [get_ports CH_AUX_DAC_SCLK]
set_property PACKAGE_PIN E16 [get_ports CH_AUX_DIN]
set_property PACKAGE_PIN F15 [get_ports CH_AUX_nSYNC]
#
set_property PACKAGE_PIN B16 [get_ports SYNC_SW]
set_property PACKAGE_PIN G16 [get_ports CH_SYNC_CLK]
set_property PACKAGE_PIN G14 [get_ports {CH_SYNC_DATA[7]}]
set_property PACKAGE_PIN G17 [get_ports {CH_SYNC_DATA[5]}]
set_property PACKAGE_PIN H15 [get_ports {CH_SYNC_DATA[6]}]
set_property PACKAGE_PIN H14 [get_ports {CH_SYNC_DATA[4]}]
set_property PACKAGE_PIN F18 [get_ports {CH_SYNC_DATA[3]}]
set_property PACKAGE_PIN H17 [get_ports {CH_SYNC_DATA[2]}]
set_property PACKAGE_PIN J15 [get_ports {CH_SYNC_DATA[1]}]
set_property PACKAGE_PIN G18 [get_ports {CH_SYNC_DATA[0]}]
#
set_property PACKAGE_PIN U11 [get_ports EXT_FSK_nOE]
set_property PACKAGE_PIN V10 [get_ports FSK_IN]
set_property PACKAGE_PIN P17 [get_ports COUNTER]
set_property PACKAGE_PIN V12 [get_ports EXT_TRIG_nOE]
set_property PACKAGE_PIN V11 [get_ports EXT_TRIG]
set_property PACKAGE_PIN T10 [get_ports EXT_IN_10M_nOE]
set_property PACKAGE_PIN T9 [get_ports EXT_OUT_10M_nOE]
set_property PACKAGE_PIN P15 [get_ports EXT_10M_INPUT]
set_property PACKAGE_PIN N15 [get_ports EXT_10M_OUTPUT]
#
set_property PACKAGE_PIN R10 [get_ports ADC_nCS]
set_property PACKAGE_PIN U13 [get_ports ADC_SCLK]
set_property PACKAGE_PIN U12 [get_ports ADC_SDATA]
#
set_property IOSTANDARD LVCMOS33 [get_ports BUZZER_ON_OFF]
set_property IOSTANDARD LVCMOS33 [get_ports CH1_ATT1_3]
set_property IOSTANDARD LVCMOS33 [get_ports CH1_ATT1_10]
set_property IOSTANDARD LVCMOS33 [get_ports CH1_ATT2_10]
set_property IOSTANDARD LVCMOS33 [get_ports CH1_GAIN_5]
set_property IOSTANDARD LVCMOS33 [get_ports CH2_ATT1_3]
set_property IOSTANDARD LVCMOS33 [get_ports CH2_ATT1_10]
set_property IOSTANDARD LVCMOS33 [get_ports CH2_ATT2_10]
set_property IOSTANDARD LVCMOS33 [get_ports CH2_GAIN_5]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_ADDR[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_ADDR[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_ADDR[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_ADDR[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_ADDR[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_ADDR[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_ADDR[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_ADDR[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_ADDR[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_ADDR[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_ADDR[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_ADDR[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_FPGA_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CH_SYNC_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CH_SYNC_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CH_SYNC_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CH_SYNC_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CH_SYNC_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CH_SYNC_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CH_SYNC_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CH_SYNC_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {COLUMN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {COLUMN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {COLUMN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {COLUMN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {COLUMN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HW_REV[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HW_REV[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HW_REV[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ROW[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ROW[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ROW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ROW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ROW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ROW[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports AD9122_nCS]
set_property IOSTANDARD LVCMOS25 [get_ports AD9122_nRESET]
set_property IOSTANDARD LVCMOS25 [get_ports AD9122_SCLK]
set_property IOSTANDARD LVCMOS25 [get_ports AD9122_SDIO]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_nCS]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_SDATA]
set_property IOSTANDARD LVCMOS33 [get_ports ARM_FPGA_nCS]
set_property IOSTANDARD LVCMOS33 [get_ports ARM_FPGA_nOE]
set_property IOSTANDARD LVCMOS33 [get_ports ARM_FPGA_nWE]
set_property IOSTANDARD LVCMOS33 [get_ports CH1_LED]
set_property IOSTANDARD LVCMOS33 [get_ports CH1_LOAD_PROTECT]
set_property IOSTANDARD LVCMOS33 [get_ports CH1_ON_OFF]
set_property IOSTANDARD LVCMOS33 [get_ports CH2_LED]
set_property IOSTANDARD LVCMOS33 [get_ports CH2_LOAD_PROTECT]
set_property IOSTANDARD LVCMOS33 [get_ports CH2_ON_OFF]
set_property IOSTANDARD LVCMOS33 [get_ports CH_AUX_DAC_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports CH_AUX_DIN]
set_property IOSTANDARD LVCMOS33 [get_ports CH_AUX_nSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports CH_SYNC_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CODE_SWITCH_1]
set_property IOSTANDARD LVCMOS33 [get_ports CODE_SWITCH_2]
set_property IOSTANDARD LVCMOS33 [get_ports COUNTER]
set_property IOSTANDARD LVCMOS33 [get_ports EXT_10M_INPUT]
set_property IOSTANDARD LVCMOS33 [get_ports EXT_10M_OUTPUT]
set_property IOSTANDARD LVCMOS33 [get_ports EXT_IN_10M_nOE]
set_property IOSTANDARD LVCMOS33 [get_ports EXT_FSK_nOE]
set_property IOSTANDARD LVCMOS33 [get_ports EXT_OUT_10M_nOE]
set_property IOSTANDARD LVCMOS33 [get_ports EXT_TRIG]
set_property IOSTANDARD LVCMOS33 [get_ports EXT_TRIG_nOE]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_REF_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SYS_WORK]
set_property IOSTANDARD LVCMOS33 [get_ports FSK_IN]
set_property IOSTANDARD LVCMOS33 [get_ports KEY_CODE_INT]
set_property IOSTANDARD LVCMOS33 [get_ports MODE_LED]
set_property IOSTANDARD LVDS_25 [get_ports PLL_FPGA_CLK_P]
set_property IOSTANDARD LVDS_25 [get_ports PLL_FPGA_CLK_N]
set_property IOSTANDARD LVCMOS33 [get_ports PLL_HOLD_OVER]
set_property IOSTANDARD LVCMOS33 [get_ports PLL_nCS]
set_property IOSTANDARD LVCMOS33 [get_ports PLL_REFCLK_SEL]
set_property IOSTANDARD LVCMOS33 [get_ports PLL_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports PLL_SDIO]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_LED]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_SW]


set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 1 [current_design]
set_property CONFIG_MODE SPIx1 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]



